---
title: "Trait and Allometry Data Workflow"
author: "Marcos Longo"
date: "2023-01-18"
output: html_document
---

These documents and scripts support the processing of trait and allometry data bases. The script is intended to work particularly the [TRY data base](https://www.try-db.org/TryWeb/Home.php), but it provides a framework to incorporate data from additional sources.



* [TidyTraitAllomDB.Rmd](TidyTraitAllomDB.html).  This (mostly) R Markdown script takes data downloaded from the TRY data base (plus additional sources) and apply [tidy data](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html) standards. In a tidy data set, each row represents one observation, each column represents a variable, and each cell represents a value. In addition, categorical traits are also harmonised into consistent categories and species taxonomy is standardised to the best extent possible (likely with some user input).
* [TraitTradeOffs.Rmd](TraitTradeOffs.html).  This R Markdown script takes the tidy data produced by [TidyTraitAllomDB.Rmd](TidyTraitAllomDB.html), and performs multiple analyses to identify trait trade-offs. It also runs a cluster analysis on mixed data to define plant functional types, and creates a series of plots to explore the traits.


In the future, additional utilities for analysing trait and allometry will be incorporated to this workflow.

**Important**
1. Make sure to download the directory "RUtils" available on [GitHub](https://github.com/mpaiao/TraitAllom_Workflow), and set variable `util_path` accordingly for scripts that have this variable.
2. For plotting Brazilian states in trait abundance maps (generated by [TraitTradeOffs.Rmd](TraitTradeOffs.html)), download directory "BrazilianStatesMap" available on [GitHub](https://github.com/mpaiao/TraitAllom_Workflow), and set variable `br_state_shp` accordingly for scripts that have this variable.
